slam_node:
  compute_period: 20        # ms
  max_speed_linear: 0.33    # m/s (max: 0.33 m/s)
  max_speed_angular: 1.75   # rad/s (max: 3.0 rad/s)
  wheel_radius: 2.75        # cm (current prototype's wheel has diameter of 5.5 cm approximately)
  wheel_distance: 23.0      # cm
  gear_ratio: 1980.0
  use_imu: 1                # set to 1 if you are using IMU as heading
  view_degrees: 90.0        # deg
  distance_threshold: 0.7   # m
  camera_id: 4              # camera id for opencv
  camera_width: 240         # camera width
  camera_height: 170        # camera height
  camera_quality: 10        # image quality compression to send over mqtt (0-100)
  username: "itbdelabo"     # username from web interface
  unit_name: "Unit A"       # registered unit name from web interface
  mqtt_broker_ip: "10.147.17.162"
